# Istio Authorization Policies using SPIFFE IDs from Teleport
# These policies demonstrate service-to-service authorization based on workload identities
---
# Default deny-all policy for sock-shop namespace
# This ensures only explicitly allowed traffic is permitted
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: sock-shop
spec:
  {}  # Empty spec means deny all
---
# Allow front-end to call catalogue service
# Uses SPIFFE ID to verify the calling service identity
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: catalogue-allow-frontend
  namespace: sock-shop
spec:
  selector:
    matchLabels:
      app: catalogue
  action: ALLOW
  rules:
  - from:
    - source:
        # SPIFFE ID format: spiffe://<trust-domain>/k8s/<namespace>/<service-account>
        principals:
        - "spiffe://ellinj.teleport.sh/k8s/sock-shop/front-end"
    to:
    - operation:
        methods: ["GET"]
        paths: ["/catalogue*", "/tags", "/health"]
---
# Allow catalogue to call catalogue-db
# Database access should only come from catalogue service
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: catalogue-db-allow-catalogue
  namespace: sock-shop
spec:
  selector:
    matchLabels:
      app: catalogue-db
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "spiffe://ellinj.teleport.sh/k8s/sock-shop/catalogue"
    to:
    - operation:
        ports: ["3306"]
---
# Allow front-end to call carts service
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: carts-allow-frontend
  namespace: sock-shop
spec:
  selector:
    matchLabels:
      app: carts
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "spiffe://ellinj.teleport.sh/k8s/sock-shop/front-end"
    to:
    - operation:
        methods: ["GET", "POST", "DELETE"]
        paths: ["/carts*"]
---
# Allow front-end to call orders service
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: orders-allow-frontend
  namespace: sock-shop
spec:
  selector:
    matchLabels:
      app: orders
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "spiffe://ellinj.teleport.sh/k8s/sock-shop/front-end"
    to:
    - operation:
        methods: ["GET", "POST"]
        paths: ["/orders*"]
---
# Allow external access to front-end
# This permits ingress gateway or direct LoadBalancer access
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: frontend-allow-external
  namespace: sock-shop
spec:
  selector:
    matchLabels:
      app: front-end
  action: ALLOW
  rules:
  - from:
    - source:
        # Allow from istio-ingressgateway
        namespaces: ["istio-system"]
  - {} # Also allow direct access (for LoadBalancer service)
---
# Enable strict mTLS for the entire namespace
# This ensures all communication uses Teleport-issued certificates
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: sock-shop
spec:
  mtls:
    mode: STRICT
